version: '3'

services:
  app:
    build: 
      context: node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    command: node index.js
    networks:
      - appnode-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - appnode-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    build: 
      context: db
      dockerfile: Dockerfile
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - appnode-network

networks:
  appnode-network:
    driver: bridge
