version: '3'

services:
  app:
    build: 
      context: node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - appnode-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - appnode-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  appnode-network:
    driver: bridge
